---
- name: NVIM | Get nvim
  become: true
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /usr/bin/nvim
    owner: root
    group: root
    mode: 0775

- name: NVIM | Create nvim folders
  file:
    path: '{{ ansible_env.HOME }}/{{ item }}'
    state: directory
    recurse: true
  loop:
    - '.config/nvim/'
    - '.local/share/nvim/site/autoload/'

- name: NVIM | Get vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim'

- name: NVIM | Configure nvim alias
  lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    regexp: '^alias vi='
    line: alias vi="nvim"
