requirements:
  - bash-completion
  - conky
  - feh
  - figlet
  - fonts-font-awesome
  - fonts-powerline
  - fzf
  - highlight
  - i3
  - i3lock
  - i3status
  - imagemagick
  - jq
  - nautilus
  - numlockx
  - pass
  - pavucontrol
  - pipenv
  - pulseaudio
  - python3-ipython
  - python3-neovim
  - python3-netifaces
  - scrot
  - sops
  - suckless-tools
  - terminator
  - tig
  - x11-xserver-utils
  - xautolock
  - xbacklight
  - yamllint
  - zsh
